spring.application.name=discovery-server
server.port=8761


# Eureka server should not register itself as client
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Eureka dashboard
eureka.instance.hostname=localhost

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
