spring.application.name=config-server
server.port=8888


spring.cloud.config.server.git.uri=file:///C:/Users/satya/OneDrive/Desktop/insureflow-pro/config-repo
spring.cloud.config.server.git.default-label=main

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always